theme: jekyll-theme-minimal

description: 我的学习笔记-My learning notes


############################
# --- Required options --- #
############################

# Name of website
title: Welly Grandpa's homepage

# Your name to show in the footer
author: Welly Grandpa
